spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking_core_service
    username: javatodev_development
    password: oPItyPticIAt
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

info:
  app:
    name: ${spring.application.name}

##ACTUATOR ENDPOINT CONFIGURATIONS
management:
  endpoints:
    web:
      exposure:
        include: info,health,configprops
  info:
    env:
      enabled: true

logging:
  file:
    name: '/var/log/core-banking-service/application.log'
