spring:
  datasource:
    url: jdbc:mysql://mysql_core_db:3306/banking_core_service
    username: javatodev_development
    password: oPItyPticIAt
  jpa:
    hibernate:
      ddl-auto: none

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://172.17.128.1:9411/api/v2/spans    

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://internet-banking-service-registry:8761/eureka

info:
  app:
    name: ${spring.application.name}
