spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/banking_core_user_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: javatodev_development
    password: oPItyPticIAt


  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  config:
    keycloak:
      server-url: http://localhost:8080   # remove /auth if Keycloak 17+
      realm: javatodev-internet-banking
      clientId: internet-banking-api-client
      client-secret: 69e21a34-6cfc-4efd-be0a-7411c193b82a

logging:
  file:
    name: logs/internet-banking-user-service.log
